version: "2"
services:
    webserver:
        image: buildok/nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/config:/etc/nginx
        links:
            - webapp:backend_php
    webapp:
        image: buildok/fpm
        ports:
            - "9000"
        volumes:
            - ~/projects/phpinfo:/backend_php
            - ./fpm/config:/etc/php/7.0/fpm/pool.d